const loginType = {
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_TIMED_OUT:"LOGIN_TIMED_OUT",
    LOG_OUT:"LOG_OUT",
    GET_CURRENT_USER:"GET_CURRENT_USER",
    GET_USER_SUCCESS:"GET_USER_SUCCESS",
    LOG_OUT_USER:"LOG_OUT_USER"
}

export default loginType;